# Generated by Django 3.0.5 on 2021-08-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210813_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='id',
            new_name='index',
        ),
    ]
